// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBdnA5Rkxq2nSOpI1PVQSzTrzg3Bx08WQ',
    appId: '1:976222820426:web:962750f52757f228442eb3',
    messagingSenderId: '976222820426',
    projectId: 'clarifi-369da',
    authDomain: 'clarifi-369da.firebaseapp.com',
    storageBucket: 'clarifi-369da.firebasestorage.app',
    measurementId: 'G-8BGMLJPQX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHmJBBqyI_foNMsHEm0wYTCfdn5BWkj7E',
    appId: '1:976222820426:android:37a0833b2e4673a0442eb3',
    messagingSenderId: '976222820426',
    projectId: 'clarifi-369da',
    storageBucket: 'clarifi-369da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9rB9ZWOop_d4Y5dxAxguIazeM5eE4Kt0',
    appId: '1:976222820426:ios:6dfe1f24392f088a442eb3',
    messagingSenderId: '976222820426',
    projectId: 'clarifi-369da',
    storageBucket: 'clarifi-369da.firebasestorage.app',
    iosBundleId: 'com.example.clari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9rB9ZWOop_d4Y5dxAxguIazeM5eE4Kt0',
    appId: '1:976222820426:ios:6dfe1f24392f088a442eb3',
    messagingSenderId: '976222820426',
    projectId: 'clarifi-369da',
    storageBucket: 'clarifi-369da.firebasestorage.app',
    iosBundleId: 'com.example.clari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBdnA5Rkxq2nSOpI1PVQSzTrzg3Bx08WQ',
    appId: '1:976222820426:web:c39a96cf7c59feaf442eb3',
    messagingSenderId: '976222820426',
    projectId: 'clarifi-369da',
    authDomain: 'clarifi-369da.firebaseapp.com',
    storageBucket: 'clarifi-369da.firebasestorage.app',
    measurementId: 'G-Y0RHVJ90VB',
  );
}
